# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0002_remove_myprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('upload_datetime', models.DateTimeField()),
                ('last_used', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='controlleddoc',
            name='doc_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_control.DocStatus', to_field='doc_status'),
        ),
        migrations.AddField(
            model_name='controlleddoc',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_control.DocType', to_field='doc_type'),
        ),
        migrations.AddField(
            model_name='controlleddoc',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.MyProfile'),
        ),
    ]
